name: Generate Pac-Man Contribution Graph

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Menggunakan ID commit spesifik untuk memastikan action ditemukan
      - name: Generate Pac-Man
        uses: platane/github-readme-pacman@4b08711d94b0d8a5a4c5598144214f4469796b27 # <-- INI PERUBAHAN KUNCI
        with:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OUT_PATH: 'output/pacman-contribution-graph.svg'
          OUT_PATH_DARK: 'output/pacman-contribution-graph-dark.svg'
