# File: .github/workflows/pacman.yml
# Versi final dan bersih untuk tes terakhir

name: Generate Pac-Man Contribution Graph

on:
  # Jadwal untuk berjalan otomatis setiap 12 jam
  schedule:
    - cron: "0 */12 * * *"
  # Tombol untuk menjalankan manual dari tab Actions
  workflow_dispatch:

jobs:
  generate:
    # Memberikan izin pada action untuk menulis file ke repositori
    permissions:
      contents: write

    # Menggunakan sistem operasi terbaru dari GitHub
    runs-on: ubuntu-latest

    # Daftar langkah yang akan dijalankan
    steps:
      # Langkah 1: Mengunduh kode repositori Anda agar action bisa bekerja
      - name: Check out repository
        uses: actions/checkout@v4

      # Langkah 2: Menjalankan action Pac-Man dengan ID permanen
      - name: Generate Pac-Man animation
        uses: platane/github-readme-pacman@4b08711d94b0d8a5a4c5598144214f4469796b27
        with:
          # Token otentikasi, tidak perlu diubah
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # Lokasi file output, sudah sesuai dengan README Anda
          OUT_PATH: 'output/pacman-contribution-graph.svg'
          OUT_PATH_DARK: 'output/pacman-contribution-graph-dark.svg'
