name: Generate Pac-Man Contribution Graph

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Ganti "uses" dengan path yang benar
      - name: Generate Pac-Man
        uses: platane/github-readme-pacman@main # <-- INI BAGIAN YANG DIPERBAIKI
        with:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OUT_PATH: 'output/pacman-contribution-graph.svg'
          OUT_PATH_DARK: 'output/pacman-contribution-graph-dark.svg'
