name: Workflow Test

on:
  workflow_dispatch: # Hanya bisa dijalankan manual

jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print a start message
        run: echo "✅ Workflow test started successfully."

      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Print a success message
        run: echo "✅ Checkout action was found and ran successfully!"
